import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1>Welcome!</h1>

        <h2>Tools</h2>

        <div class={styles.grid}>
            <Link href="/RandomNumber">
              <a>
                <div className={styles.cards}>
                  <Image src="/randomnumber.svg" alt="Random Number" width={80}height={80}/>
                  RandomNumber100
                </div>
              </a>
            </Link>
            <Link href="/RandomNumber2">
              <a>
                <div className={styles.cards}>
                  <Image src="/randomnumber.svg" alt="Random Number" width={80}height={80}/>
                  ManualRandomNumber
                </div>
              </a>
            </Link>
            <Link href="/SearchFilter">
              <a>
                <div className={styles.cards}>
                  <Image src="/search.svg" alt="Random Number" width={80}height={80}/>
                  SearchFilter
                </div>
              </a>
            </Link>
            <Link href="/SimpleCalculator">
              <a>
                <div className={styles.cards}>
                  <Image src="/calculator.svg" alt="Random Number" width={80}height={80}/>
                  SimpleCalculator
                </div>
              </a>
            </Link>
        </div>

      </main>
    </div>
  )
}
